# Generated by Django 5.0 on 2026-05-09 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_type', models.CharField(max_length=100, verbose_name='Тип практики')),
                ('available_slots', models.IntegerField(verbose_name='Количество мест')),
                ('description', models.TextField(verbose_name='Описание практики')),
                ('contact_person', models.CharField(max_length=100, verbose_name='Контактное лицо')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('company', models.ForeignKey(limit_choices_to={'role': 'company'}, on_delete=django.db.models.deletion.CASCADE, related_name='practice_bases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'База практики',
                'verbose_name_plural': 'Базы практик',
            },
        ),
        migrations.CreateModel(
            name='PracticeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Согласована'), ('rejected', 'Отклонена'), ('completed', 'Завершена')], default='pending', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('report_file', models.FileField(blank=True, upload_to='reports/', verbose_name='Отчёт о практике')),
                ('feedback', models.TextField(blank=True, verbose_name='Отзыв от руководителя')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('practice_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='practices.practicebase')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='practice_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявка на практику',
                'verbose_name_plural': 'Заявки на практику',
            },
        ),
    ]
