# Generated by Django 5.0 on 2026-05-09 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('requirements', models.TextField(verbose_name='Требования')),
                ('salary_min', models.IntegerField(blank=True, null=True, verbose_name='Зарплата от')),
                ('salary_max', models.IntegerField(blank=True, null=True, verbose_name='Зарплата до')),
                ('employment_type', models.CharField(choices=[('full', 'Полная занятость'), ('part', 'Частичная занятость'), ('intern', 'Стажировка')], default='full', max_length=10, verbose_name='Тип занятости')),
                ('location', models.CharField(default='Москва', max_length=200, verbose_name='Местоположение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
